"""Bounded, provider-neutral recovery for Nexus structured model output."""

from __future__ import annotations

from collections.abc import Callable, Sequence

from nexus.application.model_call_context import bind_model_call_phase
from nexus.domain.model import ModelCallPhase, ModelMessage
from nexus.domain.ports.model_gateway import ModelGateway

_MessagesForAttempt = Callable[[ModelMessage | None], Sequence[ModelMessage]]

_CATEGORY_RULES = {
    "ACTION_RELATION": "TOOL_ACTION requires an action; CONTINUE and TASK_READY require null.",
    "ACTION_SCHEMA": "The action envelope must match the frozen AgentDecision schema.",
    "COMMAND_CWD_RELATION": "command_cwd is null unless command_argv is present.",
    "COMMAND_TOOL_RELATION": "A command step uses tool_name shell, a cwd, and no target paths.",
    "EDIT_TARGET_COUNT": "An editing step targets exactly one repository-relative path.",
    "INVALID_REPOSITORY_PATH": "Repository paths must use the allowed relative form.",
    "JSON_DECODE": "Return exactly one raw JSON object without prose or a markdown fence.",
    "KIND_ENUM": "AgentDecision kind must be TOOL_ACTION, CONTINUE, or TASK_READY.",
    "NARRATIVE_AUTHORITY": "A narrative step cannot carry Tool authority.",
    "NON_FROZEN_TOOL_AUTHORITY": "Only frozen Day 4 tools may carry Plan authority.",
    "PLAN_SCHEMA": "The complete Plan must satisfy the frozen Nexus Plan contract.",
    "REQUIRED_FIELD": "Every required text field must be a non-empty string.",
    "SKILL_DUPLICATE_IDS": "selected_skill_ids must not contain duplicate identities.",
    "SKILL_IDS_SCHEMA": "selected_skill_ids must be an array of valid Skill identities.",
    "SKILL_MAX_SELECTED": "selected_skill_ids must not exceed the supplied maximum.",
    "SKILL_SUMMARY_SCHEMA": "selection_reason_summary must be a non-empty bounded string.",
    "SKILL_UNKNOWN_ID": "Every selected identity must exist in the supplied metadata.",
    "STEP_KEYS": "Every PlanStep must contain exactly the frozen PlanStep fields.",
    "STEP_SCHEMA": "Every PlanStep field must satisfy its frozen type contract.",
    "STEPS_SCHEMA": "steps must be a non-empty array of PlanStep objects.",
    "TOP_LEVEL_KEYS": "The top-level object must contain exactly the frozen fields.",
    "TOP_LEVEL_TYPE": "The structured response must be a top-level JSON object.",
}

_AGENT_RETRY_REMINDER = (
    " The approved Plan and observations remain authoritative. "
    "Do not repeat actions recorded as successful."
)


class StructuredOutputViolation(ValueError):
    """Allowlisted safe category without retaining model-authored content."""

    def __init__(self, category: str) -> None:
        if category not in _CATEGORY_RULES:
            raise ValueError("Structured-output violation category is not allowlisted.")
        self.category = category
        super().__init__(category)


async def complete_structured[ResultT](
    gateway: ModelGateway,
    *,
    phase: ModelCallPhase,
    messages_for_attempt: _MessagesForAttempt,
    parse: Callable[[str], ResultT],
) -> ResultT:
    """Generate and strictly parse, with one bounded sanitized retry."""

    feedback: ModelMessage | None = None
    for attempt in range(2):
        messages = messages_for_attempt(feedback)
        with bind_model_call_phase(phase):
            response = await gateway.complete(messages)
        try:
            return parse(response.content)
        except StructuredOutputViolation as exc:
            if attempt == 1:
                raise
            feedback = _retry_feedback(phase, exc.category)
    raise AssertionError("The bounded structured-output loop did not terminate.")


def append_retry_feedback(
    messages: Sequence[ModelMessage],
    feedback: ModelMessage | None,
) -> tuple[ModelMessage, ...]:
    """Append only the fixed sanitized feedback generated by this module."""

    return tuple(messages) if feedback is None else (*messages, feedback)


def _retry_feedback(phase: ModelCallPhase, category: str) -> ModelMessage:
    rule = _CATEGORY_RULES[category]
    agent_reminder = _AGENT_RETRY_REMINDER if phase is ModelCallPhase.AGENT_STEP else ""
    return ModelMessage(
        "user",
        "Previous structured output violated the frozen Nexus contract. "
        f"Category: {category}. Frozen rule: {rule} "
        "Regenerate one complete replacement object. Return raw JSON only. "
        "Do not quote or refer to the previous output."
        f"{agent_reminder}",
    )
