"""Async ports for Nexus-owned Day 2 business data."""

from typing import Protocol

from nexus.domain.persistence import NexusSession, Repository, Run, SessionTurn


class RepositoryRepository(Protocol):
    async def add(self, repository: Repository) -> None: ...

    async def get(self, repository_id: str) -> Repository | None: ...

    async def get_by_canonical_path(self, canonical_path: str) -> Repository | None: ...


class SessionRepository(Protocol):
    async def add(self, session: NexusSession) -> None: ...

    async def get(self, session_id: str) -> NexusSession | None: ...

    async def list_by_repository(self, repository_id: str) -> list[NexusSession]: ...

    async def update(self, session: NexusSession) -> None: ...


class RunRepository(Protocol):
    async def add(self, run: Run) -> None: ...

    async def get(self, run_id: str) -> Run | None: ...

    async def get_latest_interrupted(self, session_id: str) -> Run | None: ...

    async def has_interrupted(self, session_id: str) -> bool: ...

    async def update(self, run: Run) -> None: ...


class SessionTurnRepository(Protocol):
    async def add(self, turn: SessionTurn) -> None: ...

    async def list_by_session(self, session_id: str) -> list[SessionTurn]: ...

    async def next_sequence(self, session_id: str) -> int: ...
